#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: tingle apply
EOF
    exit 2
}

# XXX: Move to hooks/req-action.d
check_free_capacity

execd /etc/tingle/hooks/pre-apply.d

invoke_os_flavour "apply-updates"

execd /etc/tingle/hooks/post-apply.d
