#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: tingle apply
EOF
    exit 2
}

# Your native package manager should be maintaining its own change log.  
# A separate message here makes it easier to discern between updates 
# applied by tingle and those that were applied some other way.
log_info "Applying updates"

execd /etc/tingle/hooks/pre-apply.d

invoke_os_flavour "apply-updates"

execd /etc/tingle/hooks/post-apply.d
