#!/bin/bash

set -e

. "${TINGLE_PREFIX:=/usr}/lib/tingle/common"

usage() {
    cat - >&2 <<EOF
Usage: apply-updates-rpm
EOF
    exit_clean 2
}

do_or_die /usr/bin/yum update -y >/dev/null

exit_clean 0
