#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: check-updates-rpm
EOF
    exit_clean 2
}

do_or_die /usr/bin/yum clean headers >/dev/null
do_or_die /usr/bin/yum clean dbcache >/dev/null
do_or_die /usr/bin/yum clean metadata >/dev/null

TMP="${TMP_DIR}/pkg-list"

if [ ! -f $UNIMPORTANT ]; then
    do_or_die touch $UNIMPORTANT
fi
ignore_rvs=( 100 )
do_or_die /usr/bin/yum -q check-update | \
  awk '
  BEGIN {
      obsoletes = 0;
  }
  /^Obsoleting Packages/ {
      obsoletes = 1;
  }
  /^[[:alnum:]]/ {
      if (obsoletes != 1) {
          name=$1;
          version=$2;
          print name " " version;
      }
  }' | \
  grep -v -f $UNIMPORTANT | \
  sort >$TMP
cat $TMP
if [ $(cat $TMP | wc -l) -gt 0 ]; then
    exit_clean 1
fi

exit_clean 0
