#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: check-updates-rpm
EOF
    exit 2
}

do_or_die /usr/bin/yum clean headers >/dev/null
do_or_die /usr/bin/yum clean dbcache >/dev/null
do_or_die /usr/bin/yum clean metadata >/dev/null

TMP=$(mktemp tingle.XXXXXX)

if ! is_interactive ; then
    exec 1>/dev/null
    exec 2>/dev/null
fi
if [ ! -f $UNIMPORTANT ]; then
    touch $UNIMPORTANT
fi
/usr/bin/yum -q check-update | \
  awk '
  BEGIN {
      obsoletes = 0;
  }
  /^Obsoleting Packages/ {
      obsoletes = 1;
  }
  /^[[:alnum:]]/ {
      if (obsoletes != 1) {
          name=$1;
          version=$2;
          print name " " version;
      }
  }' | \
  grep -v -f $UNIMPORTANT | \
  sort >$TMP
cat $TMP
if [ $(cat $TMP | wc -l) -gt 0 ]; then
    rm -f $TMP
    exit 1
fi
exec 1>&3
exec 2>&4

rm -f $TMP
