#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: check-updates-rpm
EOF
    exit 2
}

do_or_die /usr/bin/yum clean headers
do_or_die /usr/bin/yum clean dbcache
do_or_die /usr/bin/yum clean metadata

TMP=$(mktemp tingle)

if ! is_interactive ; then
    exec 1>/dev/null
    exec 2>/dev/null
fi
if [ ! -f $UNIMPORTANT ]; then
    touch $UNIMPORTANT
fi
/usr/bin/yum -q check-update | \
  awk '/^[[:alnum:]]/ {
      name=$1;
      version=$2;
      print name " " version;
  }' | \
  grep -v -f $UNIMPORTANT | \
  sort >$TMP
cat $TMP
if [ $(cat $TMP | wc -l) -gt 0 ]; then
    rm -f $TMP
    exit 1
fi
exec 1>&3
exec 2>&4

rm -f $TMP

# vim:et:sts=4:sw=4:
