#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: check-updates-dpkg
EOF
    exit 2
}

export DEBIAN_FRONTEND=noninteractive

do_or_die /usr/bin/apt-get update

TMP=$(mktemp tingle)

if ! is_interactive ; then
    exec 2>/dev/null
fi
if [ ! -f $UNIMPORTANT ]; then
    touch $UNIMPORTANT
fi
/usr/bin/apt-get -qqs dist-upgrade | \
  awk '/^Inst/ {
      name=$2;
      version=$3;
      gsub("[\[\]]", "", version);
      print name " " version;
  }' | \
  grep -v -f $UNIMPORTANT | \
  sort >$TMP
cat $TMP
if [ $(cat $TMP | wc -l) -gt 0 ]; then
    rm -f $TMP
    exit 1
fi
exec 2>&4

rm -f $TMP

# vim:et:sts=4:sw=4:
