#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: tingle check
EOF
    exit 2
}

execd ${TINGLE_PREFIX}/lib/tingle/hooks/pre-check.d

invoke_os_flavour "check-updates"

execd ${TINGLE_PREFIX}/lib/tingle/hooks/post-check.d

# vim:et:sts=4:sw=4:
