#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: check-updates-dpkg
EOF
    exit 2
}

export DEBIAN_FRONTEND=noninteractive

do_or_die /usr/bin/apt-get update >/dev/null

TMP=$(do_or_die mktemp tingle.XXXXXX)

if [ ! -f $UNIMPORTANT ]; then
    do_or_die touch $UNIMPORTANT
fi
do_or_die /usr/bin/apt-get -qqs dist-upgrade | \
  perl -nle 'if (/^Inst ([\w\.-]+)( \[[\w\.+:~-]+\])? \(([\w\.+:~-]+)/) {
      print "$1 $3";
  }' | \
  grep -v -f $UNIMPORTANT | \
  sort >$TMP
cat $TMP
if [ $(cat $TMP | wc -l) -gt 0 ]; then
    rm -f $TMP
    exit 1
fi

rm -f $TMP
