#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: tingle check
EOF
    exit_clean 2
}

execd /etc/tingle/hooks/pre-check.d

rv=0
if ! invoke_os_flavour "check-updates" ; then
    rv=1
fi

execd /etc/tingle/hooks/post-check.d

exit_clean $rv
