#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: tingle reboot
EOF
    exit 2
}

execd /etc/tingle/hooks/pre-reboot.d

MESSAGE="This system will be rebooted in ten minutes for a "
"software update.

Please save all open work and log out."

reboot-politely 10 "$MESSAGE"

# These hooks must not take longer than ten minutes to run (for what I 
# hope are obvious reasons).
execd /etc/tingle/hooks/post-reboot.d

# vim:et:sts=4:sw=4:
