#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: tingle reboot [min]
EOF
    exit_clean 2
}

execd /etc/tingle/hooks/pre-reboot.d

min_to_reboot=$1
if [ "x$min_to_reboot" = "x" ]; then
  min_to_reboot=10
fi

MESSAGE="This system will reboot in $min_to_reboot minutes for a software update.

Please save all open work and log out."

reboot-politely $min_to_reboot "$MESSAGE"

# These hooks must not take longer than ten minutes to run (for what I 
# hope are obvious reasons).
execd /etc/tingle/hooks/post-reboot.d

exit_clean 0
