#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: tingle warm
EOF
    exit_clean 2
}

execd /etc/tingle/hooks/pre-warm.d

invoke_os_flavour "warm-cache"

execd /etc/tingle/hooks/post-warm.d

exit_clean 0
