#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: warm-cache-rpm
EOF
    exit 2
}

do_or_die /usr/bin/yum clean headers >/dev/null
do_or_die /usr/bin/yum clean dbcache >/dev/null
do_or_die /usr/bin/yum clean metadata >/dev/null

do_ignore_derp /usr/bin/yum update -qy --downloadonly >/dev/null
