#!/bin/bash

set -e

. ${TINGLE_PREFIX:="/usr"}/lib/tingle/common

usage() {
    cat - >&2 <<EOF
Usage: tingle ACTION ARG

       Valid actions include check, warm, apply, and reboot. ARG is only
       used by the reboot action.

       See tingle(8).
EOF
    exit_clean 2
}

updates_pending() {
    set +e
    ${TINGLE_PREFIX}/lib/tingle/check-updates
    rv=$?
    set -e
    if [ $rv -eq 100 ]; then
        return 0
    elif [ $rv -eq 0 ]; then
        return 1
    else
        exit_clean 1
    fi
}

if [ $# -gt 2 -o "$1" = "-h" -o "$1" = "--help" ]; then
    usage
fi

action=$1
arg=$2

case $action in
    check)
        if updates_pending ; then
            exit_clean 100
        else
            debug "No pending updates"
        fi
    ;;
    warm)
        if updates_pending >/dev/null ; then
            ${TINGLE_PREFIX}/lib/tingle/warm-cache
        fi
    ;;
    apply)
        if updates_pending >/dev/null ; then
            ${TINGLE_PREFIX}/lib/tingle/warm-cache
            ${TINGLE_PREFIX}/lib/tingle/apply-updates
        fi
    ;;
    reboot)
        if updates_pending >/dev/null ; then
            ${TINGLE_PREFIX}/lib/tingle/warm-cache
            ${TINGLE_PREFIX}/lib/tingle/apply-updates
            ${TINGLE_PREFIX}/lib/tingle/reboot $arg
        fi
    ;;
    *)
        usage
esac

exit_clean 0
