.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TINGLE\-APPLY\-UPDATES" "8" "November 2010" "" ""
.
.SH "NAME"
\fBtingle\-apply\-updates\fR \- applies pending updates
.
.P
Part of the tingle(8) suite\.
.
.SH "SYNOPSIS"
\fBtingle\fR \fBapply\fR
.
.SH "DESCRIPTION"
apply\-updates will download pending update packages if you have not already run warm\-cache\. The underlying package manager is not locked into running from its local cache for this operation, and will seek what it needs from the network if necessary\.
.
.P
Do not invoke apply\-updates unless you have prepared for an interruption to service\. (Always run this program within the confines of a maintenance window\.) Package hook scripts, like dpkg\'s prerm, will shut services down before package contents are unpacked into place\.
.
.P
The following hook scripts, if they exist, will be executed when appropriate:
.
.IP "\(bu" 4
\fB/etc/tingle/hooks/pre\-apply\.d/*\fR
.
.IP "\(bu" 4
\fB/etc/tingle/hooks/post\-apply\.d/*\fR
.
.IP "" 0
.
.P
Execution order will correspond to the lexical sort order of script file names\. Hook script failures are ignored\.
.
.SH "RETURN VALUES"
Returns non\-zero if something broke\. Run interactively for full standard error output\.
.
.SH "ENVIRONMENT"
Non\-interactive mode may be forced by setting TINGLE_NONINTERACTIVE\.
.
.SH "AUTHOR"
Saj Goonatilleke \fIsg@redu\.cx\fR
.
.SH "SEE ALSO"
tingle(8), tingle\-check\-updates(8), tingle\-reboot(8), tingle\-warm\-cache(8), reboot\-politely(8), apt\-get(8), yum(8)
