.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TINGLE" "8" "November 2010" "" ""
.
.SH "NAME"
\fBtingle\fR \- (n): a thin patch
.
.SH "SYNOPSIS"
\fBtingle\fR \fBcheck\fR | \fBwarm\fR | \fBapply\fR | \fBreboot\fR
.
.SH "DESCRIPTION"
tingle acts as a thin frontend to your operating system\'s native package manager\. Unlike native tools, the tingle program serves only a single purpose: to keep all installed software packages up to date with respect to your repository mirrors\. It does this whilst presenting a simple interface, consistent across all recognised operating systems, and is usable by human and machine operators alike\.
.
.P
tingle was designed to take aggressive charge over an environment scaling many hundreds of heterogeneous systems, where the risk and cost of a single compromised system exceeded the likelihood and cost of a faulty update (regression)\. Carefully orchestrated autonomous operation is possible with the aid of tools like Func or The Marionette Collective\.
.
.P
If precise change management is a staple of your environment, ensure your local package repositories contain only those updates you are prepared to propagate\. Alternatively, exercise thorough use of your native package manager\'s pinning capabilities\. tingle will gobble down whatever you leave in the open\.
.
.P
Site or host\-specific maintenance procedures can be condensed into tingle hook scripts and executed between the actions listed below\. For instance, a site\'s configuration management system could distribute a tingle hook to have a host temporarily check itself out of the site\'s availability monitoring system before rebooting\.
.
.P
System administrators plan maintenance (at least in part) in terms of the most drastic action they expect to perform\. The action supplied to tingle acts as a brake: a means of limiting the automaton\'s reach\.
.
.br
Supported actions include:
.
.TP
\fBcheck\fR
Check for pending updates\. See tingle\-check\-updates(8)\.
.
.TP
\fBwarm\fR
Refresh the local package cache if updates are pending\. See tingle\-warm\-cache(8)\.
.
.TP
\fBapply\fR
Warm the local package cache and apply outstanding package updates if updates are pending\. See tingle\-apply\-updates(8)\.
.
.TP
\fBreboot\fR
Warm the local package cache, apply outstanding package updates, and reboot the system if updates are pending\. See tingle\-reboot(8)\.
.
.P
\fBwarm\fR, \fBapply\fR, and \fBreboot\fR will all act as no\-ops if there are no pending updates to apply\. \fBtingle reboot\fR will only reboot the system if necessary\.
.
.SH "ERROR REPORTING"
When started interactively at the shell, tingle will pass all standard error output from its children (apt\-get, yum, and so on) through to the terminal\. This mode of operation is designed primarily for problem diagnosis\.
.
.P
tingle warnings are output to standard error and will always begin with the text, \fB[warning]\fR\. Errors will similarly begin with the text, \fB[error]\fR, or \fB[abort]\fR\.
.
.P
Abort and error conditions will both trigger non\-zero exit codes to halt program execution; the difference between the two is a plain matter of semantics:
.
.P
An error condition is raised whenever an operation is started, but fails to complete because of an unforeseen problem\. An error condition will typically originate from a child process\.
.
.P
An abort condition is raised whenever an operation is actively avoided because of a visible problem\. An abort condition will typically originate from tingle itself\.
.
.SH "ENVIRONMENT"
Non\-interactive mode may be forced by setting TINGLE_NONINTERACTIVE\.
.
.SH "AUTHOR"
Saj Goonatilleke \fIsg@redu\.cx\fR
.
.SH "SEE ALSO"
tingle\-apply\-updates(8), tingle\-check\-updates(8), tingle\-reboot(8), tingle\-warm\-cache(8), reboot\-politely(8), apt\-get(8), yum(8)
