.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "TINGLE" "8" "September 2011" "" ""
.
.SH "NAME"
\fBtingle\fR \- (n): a thin patch
.
.SH "SYNOPSIS"
\fBtingle\fR \fBcheck\fR | \fBwarm\fR | \fBapply\fR | \fBreboot\fR \fB[min]\fR
.
.SH "DESCRIPTION"
tingle is a tool for applying packaged software updates\. It works by wrapping a thin shell program around your operating system\'s native package manager\. Pesky differences between package management implementations are abstracted away to simplify patch procedure\.
.
.P
Human operators can interact with tingle at the shell, or delegate their work to automated processes that can do the same\. In either case, the actor need not bother with commands that are specific to any particular operating system\.
.
.P
tingle was designed to take aggressive charge over an environment scaling many hundreds of heterogeneous systems, where the risk and cost of a single compromised system exceeded the likelihood and cost of a faulty update\. Carefully orchestrated autonomous operation is possible with the aid of tools like Func or The Marionette Collective\.
.
.P
If precise change management is a staple of your environment, ensure your local package repositories contain only those updates you are prepared to propagate\. Alternatively, exercise thorough use of your native package manager\'s pinning capabilities\. tingle will gobble down whatever you leave in the open\.
.
.P
Site or host\-specific maintenance procedures can be condensed into tingle hook scripts and automatically executed between the actions listed below\. Hook script failures will trigger an immediate abort\.
.
.br
Hook script failures may be signalled with a non\-zero exit status\.
.
.P
The only argument tingle expects to receive is a description of the most drastic action the operator is prepared to commit to\. Supported actions include:
.
.TP
\fBcheck\fR
Check for pending updates\. See tingle\-check\-updates(8)\.
.
.TP
\fBwarm\fR
Refresh the local package cache if updates are pending\. See tingle\-warm\-cache(8)\.
.
.TP
\fBapply\fR
Warm the local package cache and apply outstanding package updates if updates are pending\. See tingle\-apply\-updates(8)\.
.
.TP
\fBreboot\fR
Warm the local package cache, apply outstanding package updates, and reboot the system if updates are pending\. See tingle\-reboot(8)\.
.
.P
\fBwarm\fR, \fBapply\fR, and \fBreboot\fR will all act as no\-ops if there are no pending updates to apply\. \fBtingle reboot\fR will only reboot the system if necessary\.
.
.SH "ERROR REPORTING"
When attached to a terminal, tingle will pass all output from its children (apt\-get, yum, and so on) through to the operator\. This mode of operation is designed primarily for problem diagnosis\.
.
.P
Output is suppressed when running detached from a terminal\. This mode of operation is suitable for use with crond\.
.
.P
tingle warnings are output to standard error and will always begin with the text, \fB[warning]\fR\. Errors will similarly begin with the text, \fB[error]\fR, or \fB[abort]\fR\. All three message classes are also written to syslog\.
.
.P
Abort and error conditions will both trigger non\-zero exit codes to halt program execution; the difference between the two is a matter of semantics:
.
.P
An error condition is raised whenever an operation is started, but fails to complete because of an unforeseen problem\. An error condition will typically originate from a child process\.
.
.P
An abort condition is raised whenever an operation is actively eschewed because of a visible problem\. An abort condition will typically originate from tingle itself\.
.
.SH "AUTHOR"
Saj Goonatilleke \fIsg@redu\.cx\fR
.
.SH "SEE ALSO"
tingle\-apply\-updates(8), tingle\-check\-updates(8), tingle\-reboot(8), tingle\-warm\-cache(8), reboot\-politely(8), apt\-get(8), yum(8)
